import type { NavLink, VisaEntry, StatItem, TestimonialItem, ServiceItem } from './types';

export const WA_NUMBER = '971504145594';

export const NAV_LINKS: NavLink[] = [
  { label: 'Home', href: '/' },
  { label: 'About us', href: '/about' },
  { label: 'Services', href: '/services' },
  { label: 'UAE Visas', href: '/visa-requirements/uae' },
  { label: 'International Visas', href: '/visa-requirements/international' },
  { label: 'Contact', href: '/contact' },
];

export const STATS: StatItem[] = [
  { value: 800, label: 'Satisfied', sublabel: 'Clients', icon: 'bi-emoji-smile-fill', iconColor: 'text-yellow-400' },
  { value: 1000, label: 'Visa Applications', sublabel: 'Assisted', icon: 'bi-file-earmark-check-fill', iconColor: 'text-cyan-400' },
  { value: 100, label: 'Partner', sublabel: 'Companies', icon: 'bi-building-fill', iconColor: 'text-green-400' },
];

export const TESTIMONIALS: TestimonialItem[] = [
  { initials: 'OH', quote: 'CorePlus handled our visa renewals and company documents with absolute professionalism. Highly efficient and reliable.', name: 'Operations Head', role: 'Golden Melano', avatarColor: 'bg-blue-600', delay: 100 },
  { initials: 'SS', quote: 'Fast, clear, and always responsive — a trusted partner for our PRO work. They make complex processes look easy.', name: 'Stella Staus', role: 'HR Manager', avatarColor: 'bg-green-600', delay: 200 },
  { initials: 'FD', quote: 'They made our trade license renewal easy and stress-free — highly recommended for any business in Dubai.', name: 'Finance Director', role: 'Chinta Fresh', avatarColor: 'bg-yellow-500', delay: 300 },
  { initials: 'AL', quote: 'Quick visa approvals and smooth coordination — we\'re very satisfied with the level of service provided.', name: 'Admin Lead', role: 'Exim Line', avatarColor: 'bg-cyan-600', delay: 400 },
  { initials: 'LH', quote: 'Excellent service, always professional. CorePlus simplifies our workflow and takes the headache out of paperwork.', name: 'Founder', role: 'The Light House', avatarColor: 'bg-gray-600', delay: 500 },
  { initials: 'HE', quote: "We've been using CorePlus for years — trustworthy, efficient, and friendly team every single time.", name: 'HR Executive', role: 'SRS', avatarColor: 'bg-red-600', delay: 600 },
];

export const SERVICES: ServiceItem[] = [
  { id: 'pro', title: 'PRO Services', description: 'Professional handling of government-related documentation, approvals, and legal processes on behalf of companies or individuals in the UAE.', image: '/images/pro image.png', icon: 'bi-briefcase-fill', iconColor: 'text-yellow-400' },
  { id: 'visa', title: 'Visa Processing', description: 'We assist in all types of UAE visa applications including: Golden Visa, Employment Visa, Residence Visa, Freelance Visa, Family Visa, and Investor Visa.', image: '/images/visa_processing 12.jpg', icon: 'bi-passport-fill', iconColor: 'text-cyan-400' },
  { id: 'company', title: 'Company Formation & Licensing', description: 'From trade license application and renewal to notarization, attestation, and establishment card services, we handle every step of your business setup.', image: '/images/business set up.jpg', icon: 'bi-building-fill-check', iconColor: 'text-green-400' },
  { id: 'global-visa', title: 'Global Visa Assistance', description: 'We provide international visa support for major destinations including Schengen countries, USA, UK, Canada, Australia, New Zealand, and more.', image: '/images/visa2.jpg', icon: 'bi-globe2', iconColor: 'text-white' },
];

export const CLIENT_LOGOS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 12];

export const VISA_DATA: VisaEntry[] = [
  // UAE Visas
  {
    id: 'family',
    title: 'Family Visa',
    image: '/images/family-visa.jpg',
    price: 'Contact for Pricing',
    category: 'uae',
    subcategories: [
      {
        label: 'Spouse Visa',
        items: ['Applicant passport copy & Photo', 'Passport cover page', 'Marriage certificate attested for wife', 'Sponsor Passport copy, Visa/ID copy', 'Salary contract (mainland) / Salary certificate (Free zone)'],
      },
      {
        label: "Children's Visa",
        items: ['Applicant passport copy & Photo', 'Passport cover page', 'Birth certificate attested for children'],
      },
      {
        label: 'Parents Visa',
        items: ['Applicant passport copy & Photo', 'Passport cover page', 'Affidavit from Embassy', 'Salary: 10k+ (Contract/Certificate)', '6-month bank statement & 2 BHK Ejari'],
      },
      {
        label: 'Servant Visa',
        items: ['Passport copy & Photo', 'Salary details (25k+ contract/cert sponsor)', '6-month bank statement', '2 BHK Ejari'],
      },
    ],
  },
  {
    id: 'golden',
    title: 'Golden Visa',
    image: '/images/golden-visa.jpg',
    price: 'Contact for Pricing',
    category: 'uae',
    subcategories: [
      {
        label: 'Salary Based Professionals',
        items: ['Passport, Photo, Visa Copy', 'Equivalency certificate', 'Salary Contract (30k basic) + Bank Statement (6mo)', 'NOC from company'],
      },
      {
        label: 'Property Owners',
        items: ['Passport, Photo, Visa Copy', 'Title deed (2M+ property)', 'Bank Statement'],
      },
      {
        label: 'Investors',
        items: ['Passport, Photo, Visa Copy', 'Investment proof (2M+ in UAE)', 'Bank Statement'],
      },
    ],
  },
  {
    id: 'employment',
    title: 'Employment Visa',
    image: '/images/employment-visa.jpg',
    price: 'Contact for Pricing',
    category: 'uae',
    requirements: ['Original Passport', 'Passport-size Photo', 'Educational Certificates', 'Offer Letter / Employment Contract', 'Medical Fitness Certificate', 'Emirates ID (for renewal)'],
  },
  {
    id: 'freelance',
    title: 'Freelance Visa',
    image: '/images/freelance-visa.jpg',
    price: 'Contact for Pricing',
    category: 'uae',
    requirements: ['Passport copy & Photo', 'Portfolio or proof of freelance work', 'Bank statements', 'Free zone registration documents'],
  },
  {
    id: 'investor',
    title: 'Investor Visa',
    image: '/images/investor-visa.jpg',
    price: 'Contact for Pricing',
    category: 'uae',
    requirements: ['Passport copy & Photo', 'Trade License copy', 'Memorandum of Association', 'Bank statements (6 months)', 'Business plan (for new companies)'],
  },
  {
    id: 'tourist-30',
    title: 'Tourist Visa (30 Days)',
    image: '/images/tourinst-visa-30-days.jpg',
    price: 'AED 350',
    category: 'uae',
    requirements: ['Passport scan (6+ months validity)', 'Photo (white background)', 'Return flight ticket', 'Hotel booking or sponsor letter'],
    processingTime: '2–3 working days',
  },
  {
    id: 'tourist-60',
    title: 'Tourist Visa (60 Days)',
    image: '/images/tourinst-visa-60-days.jpg',
    price: 'AED 700',
    category: 'uae',
    requirements: ['Passport scan (6+ months validity)', 'Photo (white background)', 'Return flight ticket', 'Hotel booking or sponsor letter'],
    processingTime: '2–3 working days',
  },
  {
    id: 'transit',
    title: 'Transit Visa',
    image: '/images/transit-visa.jpg',
    price: 'AED 170',
    category: 'uae',
    requirements: ['Passport scan', 'Onward flight booking', 'Photo'],
    processingTime: '1–2 working days',
  },
  // International Visas
  {
    id: 'schengen',
    title: 'Schengen Visa',
    image: '/images/shengan-visa-from-dubai.jpg',
    price: 'From AED 500 (Service)',
    category: 'international',
    requirements: ['Passport (scan), UAE Visa & ID (3+ months)', 'Photo (white bg), Bank Statement (3 months)', 'Hotel & Flight booking', 'Travel Insurance', 'NOC Letter'],
    processingTime: '10–15 working days',
  },
  {
    id: 'uk',
    title: 'UK Visa',
    image: '/images/uk-visa-from-dubai.jpg',
    price: 'From AED 1,100',
    category: 'international',
    flag: 'gb',
    requirements: ['Passport (scan), UAE Visa & ID (4+ months)', 'Bank Statement (3 months)', 'NOC Letter', 'Supporting Docs (Travel history, Tenancy contract)'],
    pricing: [
      { label: '6 Months', amount: 'AED 1,100' },
      { label: '2 Years', amount: 'AED 3,000' },
      { label: '5 Years', amount: 'AED 4,800' },
      { label: '10 Years', amount: 'AED 6,100' },
    ],
    processingTime: '15 working days',
  },
  {
    id: 'usa',
    title: 'USA Visa',
    image: '/images/usa-visa-from-dubai.jpg',
    price: 'AED 1,050',
    category: 'international',
    flag: 'us',
    subcategories: [
      {
        label: 'New Visa Required Documents',
        items: ['Passport (scan), Photo (2x2 inch), UAE Visa & ID', 'Interview: 6 mo Bank Statement, NOC, Family docs'],
      },
      {
        label: 'Renewal Documents',
        items: ['Old Passport with US Visa, Current Passport', 'UAE Visa, Photo, Bank Statement, NOC'],
      },
    ],
    notes: 'Price: AED 1,050 (Including Visa Fees)',
    processingTime: '2–3 weeks (Renewal)',
  },
  {
    id: 'saudi',
    title: 'Saudi Visa',
    image: '/images/soudi-visa-from-dubai.jpg',
    price: 'Contact for Pricing',
    category: 'international',
    flag: 'sa',
    requirements: ['Valid passport', 'UAE residence visa copy', 'Passport-size photograph', 'Basic travel details'],
    processingTime: '24-72 hours',
  },
  {
    id: 'canada',
    title: 'Canada Visa',
    image: '/images/canada-visa.jpg',
    price: 'Contact for Pricing',
    category: 'international',
    flag: 'ca',
    requirements: ['Passport (scan), UAE Visa & ID (6+ months)', 'Photo (white bg)', 'Bank Statement (6 months)', 'Travel history', 'NOC Letter', 'Biometrics may be required'],
    processingTime: '4–8 weeks',
  },
  {
    id: 'australia',
    title: 'Australia Visa',
    image: '/images/australia-visa.jpg',
    price: 'Contact for Pricing',
    category: 'international',
    flag: 'au',
    requirements: ['Passport (scan), UAE Visa & ID (6+ months)', 'Photo (white bg)', 'Bank Statement (6 months)', 'Travel Insurance', 'NOC Letter'],
    processingTime: '4–8 weeks',
  },
  {
    id: 'new-zealand',
    title: 'New Zealand Visa',
    image: '/images/newzland-visa.jpg',
    price: 'Contact for Pricing',
    category: 'international',
    flag: 'nz',
    requirements: ['Passport (scan), UAE Visa & ID (6+ months)', 'Photo', 'Bank Statement', 'Itinerary', 'NOC Letter'],
    processingTime: '3–6 weeks',
  },
  {
    id: 'ireland',
    title: 'Ireland Visa',
    image: '/images/ireland-visa.jpg',
    price: 'Contact for Pricing',
    category: 'international',
    flag: 'ie',
    requirements: ['Passport (scan), UAE Visa & ID (3+ months)', 'Photo (white bg)', 'Bank Statement', 'Travel Insurance', 'Hotel & Flight bookings', 'NOC Letter'],
    processingTime: '8–12 weeks',
  },
  {
    id: 'thailand',
    title: 'Thailand E-Visa',
    image: '/images/thailand-e-visa.jpg',
    price: 'AED 630',
    category: 'international',
    flag: 'th',
    requirements: ['Passport (scan), UAE Visa & ID (3+ months)', 'Photo (white bg)', '3 months Bank Statement'],
    processingTime: '7 working days',
  },
  {
    id: 'turkey',
    title: 'Turkey Visa',
    image: '/images/turkey-visa.jpg',
    price: 'AED 449 (Service) + Visa Fee',
    category: 'international',
    flag: 'tr',
    requirements: ['Passport (original), UAE Visa (6+ months)', 'Bank Statement (3 mo, wet stamp)', '2 Photos (5x6 cm)', 'NOC Letter (original)', 'Accommodation proof in UAE'],
    pricing: [
      { label: '3 Month', amount: 'AED 707' },
      { label: '1 Year', amount: 'AED 1,337' },
    ],
    processingTime: '10–15 working days',
  },
  {
    id: 'japan',
    title: 'Japan Visa',
    image: '/images/japan-visa-from-dubai.jpg',
    price: 'AED 600',
    category: 'international',
    flag: 'jp',
    requirements: ['Passport (scan), UAE Visa & ID (3+ months)', 'Photo (white bg)', 'Bank Statement (3 months)', 'Hotel & Flight bookings', 'NOC Letter'],
    processingTime: '1 week',
  },
  {
    id: 'korea',
    title: 'South Korea Visa',
    image: '/images/south-koria-visa.jpg',
    price: 'AED 630',
    category: 'international',
    flag: 'kr',
    requirements: ['Passport (scan), UAE Visa & ID (3+ months)', 'Photo (white bg)', 'Bank Statement (3 months)', 'Hotel & Flight bookings', 'NOC Letter'],
    processingTime: '1 week',
  },
  {
    id: 'malaysia',
    title: 'Malaysia Visa',
    image: '/images/malesia-visa.jpg',
    price: 'AED 600',
    category: 'international',
    flag: 'my',
    requirements: ['Passport (scan), UAE Visa & ID (3+ months)', 'Photo (white bg)', 'Bank Statement'],
    processingTime: '1 week',
  },
  {
    id: 'singapore',
    title: 'Singapore Visa',
    image: '/images/singepore-visa.jpg',
    price: 'AED 600',
    category: 'international',
    flag: 'sg',
    requirements: ['Passport (scan), UAE Visa & ID (3+ months)', 'Photo (white bg)', 'Bank Statement', 'Hotel & Flight bookings'],
    processingTime: '1 week',
  },
  {
    id: 'china',
    title: 'China Visa',
    image: '/images/china-visa.jpg',
    price: 'AED 600',
    category: 'international',
    flag: 'cn',
    requirements: ['Passport (scan), UAE Visa & ID (3+ months)', 'Photo (white bg)', 'Bank Statement', 'Hotel & Flight bookings', 'NOC Letter'],
    processingTime: '1 week',
  },
  {
    id: 'brazil',
    title: 'Brazil Visa',
    image: '/images/brazil-visa.jpg',
    price: 'Contact for Pricing',
    category: 'international',
    flag: 'br',
    requirements: ['Passport (original), UAE Visa & ID (6+ months)', 'Photo', 'Bank Statement', 'Yellow Fever Vaccination Certificate', 'Hotel & Flight bookings', 'NOC Letter'],
    processingTime: '4–6 weeks',
  },
];
